version: '3.5'

services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build: ./requirements/mariadb/
    env_file:
      - .env
    # user: root
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"

  nginx:
    container_name: nginx
    networks:
      - inception
    depends_on:
      - wordpress
    build: ./requirements/nginx/
    env_file:
      - .env
    ports:
      - "443:443"
    restart: on-failure

  wordpress:
    container_name: wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    build: ./requirements/wordpress/
    env_file:
      - .env
    expose:
      - "9000"
    restart: on-failure

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/darrensdev/inception_volumes/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'
      device: '/home/darrensdev/inception_volumes/mariadb'

networks:
  inception:
    driver: bridge
