version: '3.5'

services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build: ./requirements/mariadb/
    image: mariadb
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"

  nginx:
    container_name: nginx
    networks:
      - inception
    depends_on:
      - wordpress
      - hugo
      - adminer
    volumes:
      - wordpress:/var/www
      - hugo:/var/www/hugo
    build: ./requirements/nginx/
    image: nginx
    env_file:
      - .env
    ports:
      - "443:443"
    restart: on-failure

  redis:
    container_name: redis
    networks:
      - inception
    build: ./requirements/bonus/redis/
    image: redis
    env_file:
      - .env
    expose:
      - "6379"
    restart: on-failure

  vsftpd:
    container_name: vsftpd
    networks:
      - inception
    depends_on:
      - wordpress
    build: ./requirements/bonus/ftp-server/
    image: vsftpd
    volumes:
      - wordpress:/var/www/html
    ports:
      - "21:21"
      - "60000-60100:60000-60100"
    restart: always

  hugo:
    container_name: hugo
    networks:
      - inception
    build: ./requirements/bonus/hugo-static-website/
    volumes:
      - hugo:/var/www/hugo
    restart: on-failure

  wordpress:
    container_name: wordpress
    networks:
      - inception
    depends_on:
      - mariadb
      - redis
    volumes:
      - wordpress:/var/www
    build: ./requirements/wordpress/
    image: wordpress
    env_file:
      - .env
    expose:
      - "9000"
    restart: on-failure

  adminer:
    container_name: adminer
    networks:
      - inception
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    build: ./requirements/bonus/adminer/
    restart: on-failure

  prometheus:
    container_name: prometheus
    networks:
      - inception
    build: ./requirements/bonus/prometheus/
    volumes:
      - prometheus:/prometheus
      - ./requirements/bonus/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/darrensdev/inception_volumes/wordpress'

  mariadb:
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'
      device: '/home/darrensdev/inception_volumes/mariadb'

  hugo:
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'
      device: '/home/darrensdev/inception_volumes/public'

  prometheus:
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'
      device: '/home/darrensdev/inception_volumes/prometheus'

networks:
  inception:
    name: inception
    driver: bridge

###   here the different drivers available for docker-compose:    ###
###   https://chat.openai.com/c/f41bdb90-93ac-400f-b216-645f436edb7e   ###
